### ISSUE TITLE
Refactor meetup-calendar to use new Meetup.com OAuth API

### ISSUE THREAD

**Issue by munen** [munen/meetup-calendar#4]
@ColumbusGoClub @ottodevs @cvic @telmich I'm taking the liberty to CC you in on this message, because you have either contributed to meetup-calendar or starred it on Github.

Meetup has informed me(email is below) that they are changing their API policy and that applications using token based auth will stop working on August 15th 2019. They say all applications need to be updated using the new OAuth API.

Personally, I'm still a happy user of this little application, but I'm unable to work on this on such short notice. If any of you has the time or knows of a suitable alternative, I'd be happy for a PR or suggestion.

Thank you for your time and consideration. All the best,
Alain

![image](https://user-images.githubusercontent.com/505721/61579897-a142a480-ab0b-11e9-8544-f9a742e07a74.png)

**Comment by Fraze** [comment]
Thanks for keeping us in the loop (@ColumbusGoClub is my other account). Alas, I'll be leaving for a four month hike in a few days, so no time on my end. However, perhaps if you applied for the OAuth consumer account before august 15th, you could just hang on to it until you were able to use it.

**Comment by munen** [comment]
@Fraze A four month hike sounds like a blast! We're going to hike in Glarus, Switzerland next week, too. Have a great time \(^_^)/

**Comment by munen** [comment]
@Fraze (cc @ottodevs @cvic @telmich) I'm happy to report that I've refactored `meetup-calendar` in time before meetup.com transitions to to the new API.

The application has now become simpler to host yourself - it uses only a public API (no more need for an API key).

Some notes:

- The application and the parameters are backwards compatible. So if you're using the hosted version somewher, there's nothing you have to change
- I've moved the repository from munen/meetup-calendar to twohundredok/meetup-calendar
- Next to returning HTML tables, `meetup-calendar` now also supports returning a simple JSON array of the meetup events
- I took the opportunity to overhaul the documentation

In case you're using this project, you're good to go^^

**Comment by munen** [comment]
Closing this issue, because it's done.
